apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-aypk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-aypk
    app.kubernetes.io/part-of: cin4s-839-0069-app
  name: devfile-sample-aypk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-aypk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-aypk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0069-tenant/cin4s-839-0069-app/devfile-sample-aypk@sha256:687471fbe39472327d7cf0d4c8e3aee2905569de126787c2366acaf02e9c92a1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
