apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-aypk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0069-tenant/cin4s-839-0069-app/devfile-sample-aypk@sha256:687471fbe39472327d7cf0d4c8e3aee2905569de126787c2366acaf02e9c92a1
        name: my-nodejs
        resources: {}
status: {}
